spring:
  threads:
    virtual:
      enabled: true


  datasource:
    url: jdbc:postgresql://localhost:5438/testing-app
    username: postgres
    password: Testing@APP@15112003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
